/**
 * Public Holidays Router
 * Manages company and public holiday calendar
 */
import { router } from "../_core/trpc";
import { createFeatureRestrictedProcedure } from "../middleware/enhancedRbac";
import { z } from "zod";
import { getPool } from "../db";
import { v4 as uuidv4 } from "uuid";
import { TRPCError } from "@trpc/server";
import Holidays from "date-holidays";

function pool() {
  const p = getPool();
  if (!p) throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR', message: 'Database not available' });
  return p;
}

const hrView = createFeatureRestrictedProcedure("employees:view");
const hrWrite = createFeatureRestrictedProcedure("employees:edit");

function getCountryCode(country: string | null | undefined) {
  const configuredCountry = country?.trim();
  if (!configuredCountry) return "KE";

  const normalized = configuredCountry.toLowerCase();
  const countries = new Holidays().getCountries();
  const match = Object.entries(countries).find(([code, name]) =>
    code.toLowerCase() === normalized || name.toLowerCase() === normalized
  );
  if (!match) {
    throw new TRPCError({
      code: "PRECONDITION_FAILED",
      message: `No public holiday calendar is available for organization country "${configuredCountry}"`,
    });
  }
  return match[0];
}

async function ensureLocalHolidays(
  organizationId: string | null | undefined,
  year: number,
  userId: string,
) {
  if (!organizationId) {
    return { countryCode: "KE", countryName: "Kenya", created: 0 };
  }

  const p = pool();
  const [organizationRows] = await p.query(
    "SELECT country FROM organizations WHERE id = ? LIMIT 1",
    [organizationId],
  ) as [Array<{ country: string | null }> | undefined, unknown];
  const countryCode = getCountryCode(organizationRows?.[0]?.country);
  const holidayProvider = new Holidays(countryCode, { types: ["public"] });
  const countryName = new Holidays().getCountries()[countryCode];
  const localHolidays = holidayProvider.getHolidays(year, "en")
    .filter((holiday) => holiday.type === "public");

  if (!localHolidays.length) {
    throw new TRPCError({
      code: "PRECONDITION_FAILED",
      message: `No public holidays are configured for ${countryName} in ${year}`,
    });
  }

  const [generatedRows] = await p.query(
    "SELECT DISTINCT sourceCountry FROM publicHolidays WHERE organizationId = ? AND year = ? AND isAutoGenerated = 1",
    [organizationId, year],
  ) as [Array<{ sourceCountry: string | null }> | undefined, unknown];
  if (generatedRows?.length && generatedRows.every((row) => row.sourceCountry === countryCode)) {
    return { countryCode, countryName, created: 0 };
  }

  if (generatedRows?.length) {
    await p.query(
      "DELETE FROM publicHolidays WHERE organizationId = ? AND year = ? AND isAutoGenerated = 1",
      [organizationId, year],
    );
  }

  for (const holiday of localHolidays) {
    const date = holiday.date.slice(0, 10);
    await p.query(
      `INSERT INTO publicHolidays
        (id, organizationId, name, date, year, isRecurring, type, description, createdBy, isAutoGenerated, sourceCountry)
       VALUES (?, ?, ?, ?, ?, 0, 'public', ?, ?, 1, ?)`,
      [
        uuidv4(),
        organizationId,
        holiday.name,
        date,
        year,
        `Automatically populated public holiday for ${countryName}.`,
        userId,
        countryCode,
      ],
    );
  }

  return { countryCode, countryName, created: localHolidays.length };
}

async function getOrganizationCountry(organizationId: string | null | undefined) {
  if (!organizationId) return { countryCode: "KE", countryName: "Kenya" };
  const [organizationRows] = await pool().query(
    "SELECT country FROM organizations WHERE id = ? LIMIT 1",
    [organizationId],
  ) as [Array<{ country: string | null }> | undefined, unknown];
  const countryCode = getCountryCode(organizationRows?.[0]?.country);
  return { countryCode, countryName: new Holidays().getCountries()[countryCode] };
}

export const holidaysRouter = router({
  calendarCountry: hrView.query(async ({ ctx }) =>
    getOrganizationCountry(ctx.user.organizationId)
  ),

  list: hrView
    .input(z.object({
      year: z.number().int().min(1900).max(2200).optional(),
      type: z.enum(["public", "company", "optional"]).optional(),
    }).optional())
    .query(async ({ input, ctx }) => {
      const p = pool();
      const orgId = ctx.user.organizationId;
      const year = input?.year || new Date().getFullYear();
      await ensureLocalHolidays(orgId, year, ctx.user.id);
      let query = `SELECT * FROM publicHolidays WHERE year = ? AND (organizationId = ? OR organizationId IS NULL)`;
      const params: any[] = [year, orgId];
      if (input?.type) { query += ` AND type = ?`; params.push(input.type); }
      query += ` ORDER BY date`;
      const [rows] = await p.query(query, params);
      return rows || [];
    }),

  create: hrWrite
    .input(z.object({
      name: z.string().min(1),
      date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
      year: z.number().int().optional(),
      isRecurring: z.boolean().optional(),
      type: z.enum(["public", "company", "optional"]).optional(),
      description: z.string().optional(),
    }))
    .mutation(async ({ input, ctx }) => {
      const p = pool();
      const id = uuidv4();
      await p.query(
        `INSERT INTO publicHolidays (id, organizationId, name, date, year, isRecurring, type, description, createdBy) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [id, ctx.user.organizationId, input.name, input.date, input.year ?? Number(input.date.slice(0, 4)), input.isRecurring ? 1 : 0, input.type || "company", input.description || null, ctx.user.id]
      );
      return { id };
    }),

  update: hrWrite
    .input(z.object({
      id: z.string(),
      name: z.string().optional(),
      date: z.string().optional(),
      type: z.enum(["public", "company", "optional"]).optional(),
      description: z.string().optional(),
      isRecurring: z.boolean().optional(),
    }))
    .mutation(async ({ input }) => {
      const p = pool();
      const sets: string[] = [];
      const params: any[] = [];
      if (input.name) { sets.push("name = ?"); params.push(input.name); }
      if (input.date) { sets.push("date = ?"); params.push(input.date); }
      if (input.type) { sets.push("type = ?"); params.push(input.type); }
      if (input.description !== undefined) { sets.push("description = ?"); params.push(input.description); }
      if (input.isRecurring !== undefined) { sets.push("isRecurring = ?"); params.push(input.isRecurring ? 1 : 0); }
      if (sets.length === 0) return { success: true };
      params.push(input.id);
      await p.query(`UPDATE publicHolidays SET ${sets.join(", ")} WHERE id = ?`, params);
      return { success: true };
    }),

  delete: hrWrite
    .input(z.object({ id: z.string() }))
    .mutation(async ({ input }) => {
      const p = pool();
      await p.query(`DELETE FROM publicHolidays WHERE id = ?`, [input.id]);
      return { success: true };
    }),

  // Check if a date is a holiday
  isHoliday: hrView
    .input(z.object({ date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/) }))
    .query(async ({ input, ctx }) => {
      const p = pool();
      await ensureLocalHolidays(ctx.user.organizationId, Number(input.date.slice(0, 4)), ctx.user.id);
      const [rows] = await p.query(
        `SELECT * FROM publicHolidays WHERE date = ? AND (organizationId = ? OR organizationId IS NULL) LIMIT 1`,
        [input.date, ctx.user.organizationId]
      ) as [any[] | undefined, any];
      const holidayRows = Array.isArray(rows) ? rows : [];
      return { isHoliday: holidayRows.length > 0, holiday: holidayRows[0] || null };
    }),
});
