#!/bin/bash

# Deploy Dist Index JS Script
# This script combines encoded chunk files and deploys the index.js file

echo "=========================================="
echo "DEPLOYMENT INSTRUCTIONS"
echo "=========================================="
echo ""
echo "STEP 1: Upload the following chunk files to the server:"
echo "/home3/kiiniafr/public_html/Kiini/"
echo ""
echo "Required chunk files:"
for i in {001..028}; do
  echo "  - chunk-$i.txt"
done
echo ""
echo "Use SCP command:"
echo "scp chunk-*.txt melitec1@kiini.africa:/home3/kiiniafr/public_html/Kiini/"
echo ""
echo "=========================================="
echo "STEP 2: Execute the following on the server:"
echo "=========================================="
echo ""
echo "cd /home3/kiiniafr/public_html/Kiini/"
echo "cat chunk-*.txt > dist-index-js.b64"
echo "certutil -decode dist-index-js.b64 dist-index-js.gz"
echo "gunzip -c dist-index-js.gz > dist/index.js.new"
echo "mv dist/index.js.new dist/index.js"
echo ""
echo "=========================================="
echo "STEP 3: Verification"
echo "=========================================="
echo ""
echo "Verify the deployment:"
echo "ls -lh /home3/kiiniafr/public_html/Kiini/dist/index.js"
echo "head -20 /home3/kiiniafr/public_html/Kiini/dist/index.js"
echo ""
echo "=========================================="
echo "DEPLOYMENT COMPLETE"
echo "=========================================="
echo ""
echo "The index.js file has been successfully deployed to:"
echo "/home3/kiiniafr/public_html/Kiini/dist/index.js"
echo ""
