-- Document numbers are generated by the server and must be unique in storage.
ALTER TABLE `invoices` ADD UNIQUE INDEX `invoice_number_unique_idx` (`invoiceNumber`);
ALTER TABLE `estimates` ADD UNIQUE INDEX `estimate_number_unique_idx` (`estimateNumber`);
ALTER TABLE `expenses` ADD UNIQUE INDEX `expense_number_unique_idx` (`expenseNumber`);
ALTER TABLE `receipts` ADD UNIQUE INDEX `receipt_number_unique_idx` (`receiptNumber`);
ALTER TABLE `creditNotes` ADD UNIQUE INDEX `credit_note_number_unique_idx` (`creditNoteNumber`);
ALTER TABLE `debitNotes` ADD UNIQUE INDEX `debit_note_number_unique_idx` (`debitNoteNumber`);
ALTER TABLE `proposals` ADD UNIQUE INDEX `proposal_number_unique_idx` (`proposalNumber`);
ALTER TABLE `quotations` ADD UNIQUE INDEX `quotation_rfq_number_unique_idx` (`rfqNo`);
ALTER TABLE `grnRecords` ADD UNIQUE INDEX `grn_number_unique_idx` (`grnNo`);
ALTER TABLE `deliveryNotes` ADD UNIQUE INDEX `delivery_note_number_unique_idx` (`dnNo`);
ALTER TABLE `workOrders` ADD UNIQUE INDEX `work_order_number_unique_idx` (`workOrderNumber`);
ALTER TABLE `purchaseOrders` ADD UNIQUE INDEX `purchase_order_number_unique_idx` (`poNumber`);
ALTER TABLE `lpos` ADD UNIQUE INDEX `lpo_number_unique_idx` (`lpoNumber`);
ALTER TABLE `employees` ADD UNIQUE INDEX `employee_number_unique_idx` (`employeeNumber`);