CREATE TABLE IF NOT EXISTS `documents` (
  `id` VARCHAR(64) NOT NULL,
  `organizationId` VARCHAR(64),
  `documentName` VARCHAR(255) NOT NULL,
  `documentType` ENUM('contract','agreement','proposal','template','invoice','receipt','other') DEFAULT 'other',
  `fileUrl` VARCHAR(500) NOT NULL,
  `fileSize` INT DEFAULT 0,
  `mimeType` VARCHAR(100),
  `linkedEntityType` VARCHAR(100),
  `linkedEntityId` VARCHAR(64),
  `linkedClientId` VARCHAR(64),
  `linkedProjectId` VARCHAR(64),
  `linkedInvoiceId` VARCHAR(64),
  `uploadedBy` VARCHAR(64) NOT NULL,
  `currentVersion` INT DEFAULT 1,
  `status` ENUM('active','archived','deleted') DEFAULT 'active',
  `expiryDate` TIMESTAMP NULL,
  `requiresSignature` TINYINT DEFAULT 0,
  `isSigned` TINYINT DEFAULT 0,
  `signedDate` TIMESTAMP NULL,
  `signedBy` VARCHAR(64),
  `tags` TEXT,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_document_type` (`documentType`),
  KEY `idx_entity` (`linkedEntityType`,`linkedEntityId`),
  KEY `idx_client_id` (`linkedClientId`),
  KEY `idx_project_id` (`linkedProjectId`),
  KEY `idx_uploaded_by` (`uploadedBy`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;