-- Migration: Fix Schema Foreign Key Conflicts
-- Resolves column type mismatches and missing table references

SET FOREIGN_KEY_CHECKS=0;

-- Fix dashboardLayouts - drop foreign keys and modify columns
SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = 'dashboardLayouts' AND CONSTRAINT_NAME = 'dashboardLayouts_ibfk_1') = 1, 'ALTER TABLE `dashboardLayouts` DROP FOREIGN KEY `dashboardLayouts_ibfk_1`', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = 'dashboardLayouts' AND CONSTRAINT_NAME = 'dashboardLayouts_ibfk_2') = 1, 'ALTER TABLE `dashboardLayouts` DROP FOREIGN KEY `dashboardLayouts_ibfk_2`', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'dashboardLayouts' AND COLUMN_NAME = 'user_id') = 1, 'ALTER TABLE `dashboardLayouts` MODIFY COLUMN `user_id` varchar(64)', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'dashboardLayouts' AND COLUMN_NAME = 'id') = 1, 'ALTER TABLE `dashboardLayouts` MODIFY COLUMN `id` varchar(64)', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- Fix dashboardWidgets - drop foreign keys and modify columns
SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = 'dashboardWidgets' AND CONSTRAINT_NAME = 'dashboardWidgets_ibfk_1') = 1, 'ALTER TABLE `dashboardWidgets` DROP FOREIGN KEY `dashboardWidgets_ibfk_1`', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = 'dashboardWidgets' AND CONSTRAINT_NAME = 'dashboardWidgets_ibfk_2') = 1, 'ALTER TABLE `dashboardWidgets` DROP FOREIGN KEY `dashboardWidgets_ibfk_2`', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'dashboardWidgets' AND COLUMN_NAME = 'layout_id') = 1, 'ALTER TABLE `dashboardWidgets` MODIFY COLUMN `layout_id` varchar(64)', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'dashboardWidgets' AND COLUMN_NAME = 'id') = 1, 'ALTER TABLE `dashboardWidgets` MODIFY COLUMN `id` varchar(64)', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- Fix payslips - drop foreign key and modify columns
SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = 'payslips' AND CONSTRAINT_NAME = 'fk_payslip_employee') = 1, 'ALTER TABLE `payslips` DROP FOREIGN KEY `fk_payslip_employee`', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'payslips' AND COLUMN_NAME = 'employeeId') = 1, 'ALTER TABLE `payslips` MODIFY COLUMN `employeeId` varchar(64)', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- Fix attendance - drop foreign keys and modify columns
SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = 'attendance' AND CONSTRAINT_NAME = 'attendance_ibfk_1') = 1, 'ALTER TABLE `attendance` DROP FOREIGN KEY `attendance_ibfk_1`', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = 'attendance' AND CONSTRAINT_NAME = 'fk_attendance_employee') = 1, 'ALTER TABLE `attendance` DROP FOREIGN KEY `fk_attendance_employee`', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = 'attendance' AND CONSTRAINT_NAME = 'attendance_ibfk_2') = 1, 'ALTER TABLE `attendance` DROP FOREIGN KEY `attendance_ibfk_2`', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'attendance' AND COLUMN_NAME = 'employeeId') = 1, 'ALTER TABLE `attendance` MODIFY COLUMN `employeeId` varchar(64)', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'attendance' AND COLUMN_NAME = 'id') = 1, 'ALTER TABLE `attendance` MODIFY COLUMN `id` varchar(64)', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- Recreate valid foreign keys
SET @sql = IF(
	(SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'employees' AND COLUMN_NAME = 'id') = 1
	AND (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'employees' AND COLUMN_NAME = 'id' AND SEQ_IN_INDEX = 1) = 0,
	'ALTER TABLE `employees` ADD UNIQUE INDEX `employees_id_fk_idx` (`id`)',
	'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @employee_id_column_definition = (
	SELECT CONCAT(
		COLUMN_TYPE,
		IF(CHARACTER_SET_NAME IS NULL, '', CONCAT(' CHARACTER SET ', CHARACTER_SET_NAME)),
		IF(COLLATION_NAME IS NULL, '', CONCAT(' COLLATE ', COLLATION_NAME))
	)
	FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'employees' AND COLUMN_NAME = 'id'
	LIMIT 1
);
SET @sql = IF(
	@employee_id_column_definition IS NOT NULL
	AND (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'payslips' AND COLUMN_NAME = 'employeeId') = 1,
	CONCAT('ALTER TABLE `payslips` MODIFY COLUMN `employeeId` ', @employee_id_column_definition, ' NOT NULL'),
	'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF(
	@employee_id_column_definition IS NOT NULL
	AND (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'attendance' AND COLUMN_NAME = 'employeeId') = 1,
	CONCAT('ALTER TABLE `attendance` MODIFY COLUMN `employeeId` ', @employee_id_column_definition, ' NOT NULL'),
	'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'dashboardLayouts' AND COLUMN_NAME = 'user_id') = 1 AND (SELECT COUNT(*) FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = 'dashboardLayouts' AND CONSTRAINT_NAME = 'dashboardLayouts_user_fk') = 0, 'ALTER TABLE `dashboardLayouts` ADD CONSTRAINT `dashboardLayouts_user_fk` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'dashboardWidgets' AND COLUMN_NAME = 'layout_id') = 1 AND (SELECT COUNT(*) FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = 'dashboardWidgets' AND CONSTRAINT_NAME = 'dashboardWidgets_layout_fk') = 0, 'ALTER TABLE `dashboardWidgets` ADD CONSTRAINT `dashboardWidgets_layout_fk` FOREIGN KEY (`layout_id`) REFERENCES `dashboardLayouts`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'payslips' AND COLUMN_NAME = 'employeeId') = 1 AND (SELECT COUNT(*) FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = 'payslips' AND CONSTRAINT_NAME = 'payslips_employee_fk') = 0, 'ALTER TABLE `payslips` ADD CONSTRAINT `payslips_employee_fk` FOREIGN KEY (`employeeId`) REFERENCES `employees`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'attendance' AND COLUMN_NAME = 'employeeId') = 1 AND (SELECT COUNT(*) FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = 'attendance' AND CONSTRAINT_NAME = 'attendance_employee_fk') = 0, 'ALTER TABLE `attendance` ADD CONSTRAINT `attendance_employee_fk` FOREIGN KEY (`employeeId`) REFERENCES `employees`(`id`) ON DELETE CASCADE ON UPDATE CASCADE', 'SELECT 1');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET FOREIGN_KEY_CHECKS=1;
