-- P9 annual tax forms used by the HR payroll and tax compliance modules.
CREATE TABLE IF NOT EXISTS `p9_forms` (
  `id` varchar(64) NOT NULL,
  `organizationId` varchar(64) NOT NULL,
  `employeeId` varchar(64) NOT NULL,
  `taxYear` int NOT NULL,
  `taxNumber` varchar(30),
  `grossIncome` int NOT NULL,
  `totalDeductions` int NOT NULL,
  `paye` int DEFAULT 0,
  `nssf` int DEFAULT 0,
  `shif` int DEFAULT 0,
  `housingLevy` int DEFAULT 0,
  `reliefs` int DEFAULT 0,
  `netTaxPayable` int NOT NULL,
  `numberOfPayslips` int DEFAULT 12,
  `htmlContent` text,
  `pdfUrl` varchar(500),
  `sentTo` varchar(320),
  `sentAt` timestamp NULL,
  `status` enum('draft','generated','sent','received') NOT NULL DEFAULT 'draft',
  `generatedBy` varchar(64),
  `generatedAt` timestamp NULL,
  `notes` text,
  `createdAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `p9_emp_idx` (`employeeId`),
  KEY `tax_year_idx` (`taxYear`),
  KEY `p9_status_idx` (`status`),
  KEY `p9_org_idx` (`organizationId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;