CREATE TABLE IF NOT EXISTS `approval_levels` (
  `id` varchar(36) NOT NULL,
  `workflow_id` varchar(36) NOT NULL,
  `organization_id` varchar(36) NOT NULL,
  `level_number` int NOT NULL,
  `level_name` varchar(100),
  `approval_type` varchar(50) NOT NULL,
  `approver_roles` json NOT NULL,
  `approver_user_ids` json,
  `escalation_days` int,
  `conditions` json,
  `requires_comment` boolean DEFAULT false,
  `allow_approve_partially` boolean DEFAULT false,
  `notification_template` varchar(100),
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_workflow_id` (`workflow_id`),
  INDEX `idx_org_id` (`organization_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `approval_requests` (
  `id` varchar(36) NOT NULL,
  `organization_id` varchar(36) NOT NULL,
  `workflow_id` varchar(36) NOT NULL,
  `entity_type` varchar(100) NOT NULL,
  `entity_id` varchar(36) NOT NULL,
  `status` varchar(50) NOT NULL,
  `current_level` int NOT NULL DEFAULT 1,
  `total_levels` int NOT NULL,
  `progress_percentage` int DEFAULT 0,
  `completed_levels` int DEFAULT 0,
  `requested_by` varchar(36) NOT NULL,
  `requested_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `reason` text,
  `amount` int,
  `due_date` timestamp NULL,
  `completed_at` timestamp NULL,
  `metadata` json,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_org_id` (`organization_id`),
  INDEX `idx_entity` (`entity_type`, `entity_id`),
  INDEX `idx_status` (`status`),
  INDEX `idx_current_level` (`current_level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `approval_actions` (
  `id` varchar(36) NOT NULL,
  `approval_request_id` varchar(36) NOT NULL,
  `organization_id` varchar(36) NOT NULL,
  `level_number` int NOT NULL,
  `approver_id` varchar(36) NOT NULL,
  `approver_role` varchar(100),
  `action` varchar(50) NOT NULL,
  `status` varchar(50) NOT NULL,
  `comment` text,
  `decision_amount` int,
  `due_date` timestamp NULL,
  `action_date` timestamp NULL,
  `escalated_to` varchar(36),
  `escalation_reason` varchar(255),
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_approval_request_id` (`approval_request_id`),
  INDEX `idx_approver_id` (`approver_id`),
  INDEX `idx_status` (`status`),
  INDEX `idx_level` (`level_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `approval_notifications` (
  `id` varchar(36) NOT NULL,
  `organization_id` varchar(36) NOT NULL,
  `approval_request_id` varchar(36),
  `approval_action_id` varchar(36),
  `recipient_id` varchar(36) NOT NULL,
  `type` varchar(50) NOT NULL,
  `title` varchar(255) NOT NULL,
  `message` text NOT NULL,
  `is_read` boolean DEFAULT false,
  `read_at` timestamp NULL,
  `delivery_channels` json,
  `delivery_status` json,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sent_at` timestamp NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_recipient_id` (`recipient_id`),
  INDEX `idx_approval_request_id` (`approval_request_id`),
  INDEX `idx_type` (`type`),
  INDEX `idx_is_read` (`is_read`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `approval_audit_log` (
  `id` varchar(36) NOT NULL,
  `organization_id` varchar(36) NOT NULL,
  `approval_request_id` varchar(36) NOT NULL,
  `action` varchar(100) NOT NULL,
  `performed_by` varchar(36),
  `details` json,
  `ip_address` varchar(45),
  `user_agent` varchar(500),
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_org_id` (`organization_id`),
  INDEX `idx_approval_request_id` (`approval_request_id`),
  INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `approval_metrics` (
  `id` varchar(36) NOT NULL,
  `organization_id` varchar(36) NOT NULL,
  `workflow_id` varchar(36),
  `avg_approval_time` int,
  `median_approval_time` int,
  `total_requests` int DEFAULT 0,
  `approved_requests` int DEFAULT 0,
  `rejected_requests` int DEFAULT 0,
  `partially_approved_requests` int DEFAULT 0,
  `pending_requests` int DEFAULT 0,
  `approval_rate` int,
  `rejection_rate` int,
  `escalation_rate` int,
  `period` varchar(20),
  `period_date` timestamp NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_org_id` (`organization_id`),
  INDEX `idx_workflow_id` (`workflow_id`),
  INDEX `idx_period` (`period`, `period_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
