CREATE TABLE IF NOT EXISTS `nonSalesInflows` (
  `id` varchar(64) NOT NULL,
  `organizationId` varchar(64) NOT NULL,
  `referenceNumber` varchar(100) NOT NULL,
  `inflowType` enum('donation','other_income','equity_injection','deferred_loan') NOT NULL,
  `status` enum('posted','reversed') NOT NULL DEFAULT 'posted',
  `description` varchar(500) NOT NULL,
  `amountCents` bigint NOT NULL,
  `currency` varchar(10) NOT NULL,
  `usdToOrganizationFxRate` decimal(18,8) NULL,
  `taxStatus` enum('taxable','tax_exempt','equity_injection','deferred_loan') NOT NULL,
  `cashAccountId` varchar(64) NOT NULL,
  `categoryAccountId` varchar(64) NOT NULL,
  `bankAccountId` varchar(64) NULL,
  `sourceBankTransactionId` varchar(64) NULL,
  `complianceMetadata` json NULL,
  `receivedAt` datetime NOT NULL,
  `journalEntryId` varchar(64) NOT NULL,
  `reversalJournalEntryId` varchar(64) NULL,
  `reversedAt` datetime NULL,
  `reversedBy` varchar(64) NULL,
  `reversalReason` varchar(500) NULL,
  `createdBy` varchar(64) NOT NULL,
  `createdAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `non_sales_inflow_org_ref_uq` (`organizationId`,`referenceNumber`),
  UNIQUE KEY `non_sales_inflow_bank_tx_uq` (`sourceBankTransactionId`),
  KEY `non_sales_inflow_org_date_idx` (`organizationId`,`receivedAt`),
  KEY `non_sales_inflow_org_status_idx` (`organizationId`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
