SET @has_is_auto_generated = (
  SELECT COUNT(*) FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'publicHolidays'
    AND COLUMN_NAME = 'isAutoGenerated'
);
SET @add_is_auto_generated = IF(
  @has_is_auto_generated = 0,
  'ALTER TABLE `publicHolidays` ADD COLUMN `isAutoGenerated` tinyint NOT NULL DEFAULT 0',
  'SELECT 1'
);
PREPARE add_is_auto_generated_stmt FROM @add_is_auto_generated;
EXECUTE add_is_auto_generated_stmt;
DEALLOCATE PREPARE add_is_auto_generated_stmt;

SET @has_source_country = (
  SELECT COUNT(*) FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'publicHolidays'
    AND COLUMN_NAME = 'sourceCountry'
);
SET @add_source_country = IF(
  @has_source_country = 0,
  'ALTER TABLE `publicHolidays` ADD COLUMN `sourceCountry` varchar(2) NULL',
  'SELECT 1'
);
PREPARE add_source_country_stmt FROM @add_source_country;
EXECUTE add_source_country_stmt;
DEALLOCATE PREPARE add_source_country_stmt;
