CREATE TABLE IF NOT EXISTS `globalAccountingPolicies` (
  `id` varchar(32) NOT NULL,
  `country` varchar(10) NOT NULL DEFAULT 'KE',
  `fiscalYearStart` varchar(5) NOT NULL DEFAULT '01-01',
  `fiscalYearEnd` varchar(5) NOT NULL DEFAULT '12-31',
  `accountingMethod` enum('accrual','cash') NOT NULL DEFAULT 'accrual',
  `defaultCurrency` varchar(3) NOT NULL DEFAULT 'KES',
  `taxInclusiveInvoicing` tinyint NOT NULL DEFAULT 1,
  `autoReconciliation` tinyint NOT NULL DEFAULT 0,
  `requireInvoiceApproval` tinyint NOT NULL DEFAULT 1,
  `requireExpenseApproval` tinyint NOT NULL DEFAULT 1,
  `defaultPaymentTerms` varchar(20) DEFAULT 'net30',
  `depreciationMethod` enum('straight_line','declining_balance','units_of_production') DEFAULT 'straight_line',
  `capitalizedAssetThreshold` int DEFAULT 50000,
  `roundingMethod` enum('round','truncate') DEFAULT 'round',
  `retentionPeriod` int DEFAULT 7,
  `auditTrailRequired` tinyint NOT NULL DEFAULT 1,
  `allowManualJournalEntries` tinyint NOT NULL DEFAULT 1,
  `createdBy` varchar(64) NOT NULL,
  `createdAt` timestamp NOT NULL,
  `updatedBy` varchar(64) DEFAULT NULL,
  `updatedAt` timestamp DEFAULT NULL,
  PRIMARY KEY (`id`)
);
