ALTER TABLE `quotations`
  ADD COLUMN `buyerCompanyName` varchar(200) NULL,
  ADD COLUMN `buyerDepartment` varchar(200) NULL,
  ADD COLUMN `buyerContactName` varchar(255) NULL,
  ADD COLUMN `buyerContactTitle` varchar(150) NULL,
  ADD COLUMN `buyerEmail` varchar(320) NULL,
  ADD COLUMN `buyerPhone` varchar(50) NULL,
  ADD COLUMN `deliveryAddress` text NULL,
  ADD COLUMN `issueDate` varchar(30) NULL,
  ADD COLUMN `submissionDeadline` varchar(30) NULL,
  ADD COLUMN `targetDeliveryDate` varchar(30) NULL,
  ADD COLUMN `bidderLegalName` varchar(200) NULL,
  ADD COLUMN `bidderRegistrationNumber` varchar(100) NULL,
  ADD COLUMN `bidderContactName` varchar(255) NULL,
  ADD COLUMN `bidderEmail` varchar(320) NULL,
  ADD COLUMN `bidderPhone` varchar(50) NULL,
  ADD COLUMN `quoteValidityDays` int NULL DEFAULT 60,
  ADD COLUMN `quoteValidUntil` varchar(30) NULL,
  ADD COLUMN `leadTime` varchar(200) NULL,
  ADD COLUMN `lineItems` json NULL,
  ADD COLUMN `currency` varchar(3) NULL DEFAULT 'KES',
  ADD COLUMN `taxRate` decimal(5,2) NULL DEFAULT 0,
  ADD COLUMN `shippingAmount` int NULL DEFAULT 0,
  ADD COLUMN `subtotal` int NULL DEFAULT 0,
  ADD COLUMN `taxAmount` int NULL DEFAULT 0,
  ADD COLUMN `submissionFormat` varchar(200) NULL,
  ADD COLUMN `submissionMethod` varchar(100) NULL,
  ADD COLUMN `submissionEmail` varchar(320) NULL,
  ADD COLUMN `emailSubjectProtocol` text NULL,
  ADD COLUMN `mandatoryAttachments` text NULL,
  ADD COLUMN `costWeight` int NULL DEFAULT 50,
  ADD COLUMN `complianceWeight` int NULL DEFAULT 30,
  ADD COLUMN `deliveryWeight` int NULL DEFAULT 20,
  ADD COLUMN `nonBindingTerms` text NULL,
  ADD COLUMN `incoterms` varchar(100) NULL,
  ADD COLUMN `paymentTerms` text NULL,
  ADD COLUMN `settlementDays` int NULL,
  ADD COLUMN `buyerSignatoryName` varchar(255) NULL,
  ADD COLUMN `buyerSignatoryTitle` varchar(150) NULL,
  ADD COLUMN `bidderSignatoryName` varchar(255) NULL,
  ADD COLUMN `bidderSignatoryTitle` varchar(150) NULL;

ALTER TABLE `contracts`
  ADD COLUMN `terminatedAt` varchar(30) NULL,
  ADD COLUMN `terminationReason` text NULL,
  ADD COLUMN `terminatedBy` varchar(36) NULL;
