export interface LegacyColumnDefinition {
  name: string;
  definition: string;
}

export interface LegacyTableDefinition {
  name: string;
  createSql: string;
}

const legacyColumnCatalog: Record<string, LegacyColumnDefinition[]> = {
  settings: [
    { name: 'value', definition: 'longtext NULL' },
    { name: 'category', definition: 'varchar(100) NULL' },
    { name: 'description', definition: 'text NULL' },
    { name: 'updatedBy', definition: 'varchar(64) NULL' },
    { name: 'updatedAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP' },
  ],
  integration_configs: [
    { name: 'name', definition: 'varchar(200) NULL' },
    { name: 'service', definition: 'varchar(100) NULL' },
    { name: 'integrationType', definition: 'varchar(50) NULL' },
    { name: 'config', definition: 'text NULL' },
    { name: 'status', definition: "varchar(20) NULL DEFAULT 'inactive'" },
    { name: 'isActive', definition: 'tinyint NOT NULL DEFAULT 1' },
    { name: 'lastSync', definition: 'timestamp NULL' },
    { name: 'lastSyncAt', definition: 'timestamp NULL' },
    { name: 'createdBy', definition: 'varchar(64) NULL' },
    { name: 'createdAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
    { name: 'updatedAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
  ],
  notes: [
    { name: 'title', definition: 'varchar(300) NULL' },
    { name: 'content', definition: 'text NULL' },
    { name: 'category', definition: "varchar(100) NULL DEFAULT 'General'" },
    { name: 'pinned', definition: 'tinyint NOT NULL DEFAULT 0' },
    { name: 'favorite', definition: 'tinyint NOT NULL DEFAULT 0' },
    { name: 'createdBy', definition: 'varchar(64) NULL' },
    { name: 'organizationId', definition: 'varchar(64) NULL' },
    { name: 'createdAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
    { name: 'updatedAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
  ],
  recurringInvoices: [
    { name: 'accountManagerId', definition: 'varchar(64) NULL' },
  ],
  invoices: [
    { name: 'organizationId', definition: 'varchar(64) NULL' },
    { name: 'projectId', definition: 'varchar(64) NULL' },
    { name: 'category', definition: 'varchar(100) NULL' },
    { name: 'approvedBy', definition: 'varchar(64) NULL' },
    { name: 'approvedAt', definition: 'datetime NULL' },
    { name: 'accountManagerId', definition: 'varchar(64) NULL' },
    { name: 'paymentPlanId', definition: 'varchar(64) NULL' },
    { name: 'isAutoRecurring', definition: 'tinyint NULL DEFAULT 0' },
    { name: 'recurringInvoiceId', definition: 'varchar(64) NULL' },
    { name: 'clientSubscriptionId', definition: 'varchar(64) NULL' },
  ],
  users: [
    { name: 'emailVerified', definition: 'timestamp NULL' },
    { name: 'failedLoginAttempts', definition: 'int NOT NULL DEFAULT 0' },
    { name: 'lockedUntil', definition: 'timestamp NULL' },
    { name: 'lockoutCount', definition: 'int NOT NULL DEFAULT 0' },
    { name: 'emailVerificationRequired', definition: 'tinyint NOT NULL DEFAULT 0' },
    { name: 'twoFactorEnabled', definition: 'tinyint NOT NULL DEFAULT 0' },
    { name: 'twoFactorSecret', definition: 'varchar(255) NULL' },
    { name: 'customRoleId', definition: 'varchar(64) NULL' },
  ],
  customRoles: [
    { name: 'organizationId', definition: 'varchar(64) NULL' },
    { name: 'name', definition: 'varchar(100) NULL' },
    { name: 'displayName', definition: 'varchar(255) NULL' },
    { name: 'description', definition: 'text NULL' },
    { name: 'permissions', definition: 'text NULL' },
    { name: 'baseRole', definition: "varchar(50) NULL DEFAULT 'staff'" },
    { name: 'isAdvanced', definition: 'tinyint NOT NULL DEFAULT 0' },
    { name: 'isSystem', definition: 'tinyint NOT NULL DEFAULT 0' },
    { name: 'isActive', definition: 'tinyint NOT NULL DEFAULT 1' },
    { name: 'createdBy', definition: 'varchar(64) NULL' },
    { name: 'createdAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
    { name: 'updatedAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
  ],
  organizations: [
    { name: 'isArchived', definition: 'tinyint NOT NULL DEFAULT 0' },
    { name: 'archivedAt', definition: 'timestamp NULL' },
    { name: 'archivedBy', definition: 'varchar(64) NULL' },
    { name: 'logoUrl', definition: 'longtext NULL' },
    { name: 'domain', definition: 'varchar(255) NULL' },
    { name: 'contactEmail', definition: 'varchar(320) NULL' },
    { name: 'contactPhone', definition: 'varchar(50) NULL' },
    { name: 'address', definition: 'text NULL' },
    { name: 'country', definition: 'varchar(100) NULL' },
    { name: 'industry', definition: 'varchar(100) NULL' },
    { name: 'website', definition: 'varchar(255) NULL' },
    { name: 'taxId', definition: 'varchar(100) NULL' },
    { name: 'billingEmail', definition: 'varchar(320) NULL' },
    { name: 'timezone', definition: "varchar(100) NULL DEFAULT 'Africa/Nairobi'" },
    { name: 'currency', definition: "varchar(10) NULL DEFAULT 'KES'" },
    { name: 'description', definition: 'text NULL' },
    { name: 'employeeCount', definition: 'int NULL' },
    { name: 'registrationNumber', definition: 'varchar(100) NULL' },
    { name: 'paymentMethod', definition: 'varchar(50) NULL' },
    { name: 'urlMode', definition: "enum('path','subdomain') NOT NULL DEFAULT 'subdomain'" },
    { name: 'updatedAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
  ],
  payslips: [
    { name: 'payrollId', definition: 'varchar(64) NULL' },
    { name: 'payPeriod', definition: 'varchar(20) NULL' },
    { name: 'payDate', definition: 'datetime NULL' },
    { name: 'payPeriodStart', definition: 'datetime NULL' },
    { name: 'payPeriodEnd', definition: 'datetime NULL' },
    { name: 'payMonth', definition: 'datetime NULL' },
    { name: 'payslipNumber', definition: 'varchar(50) NULL' },
    { name: 'payrollDetailId', definition: 'varchar(64) NULL' },
    { name: 'allowancesBreakdown', definition: 'text NULL' },
    { name: 'deductionsBreakdown', definition: 'text NULL' },
    { name: 'htmlContent', definition: 'longtext NULL' },
  ],
  employees: [
    { name: 'country', definition: "varchar(5) DEFAULT 'KE'" },
    { name: 'gender', definition: "enum('male','female','other') NULL" },
    { name: 'maritalStatus', definition: "enum('single','married','divorced','widowed') NULL" },
    { name: 'jobGroupId', definition: 'varchar(64) NULL' },
    { name: 'probationEndDate', definition: 'datetime NULL' },
    { name: 'contractEndDate', definition: 'datetime NULL' },
    { name: 'emergencyContactName', definition: 'varchar(255) NULL' },
    { name: 'emergencyContactRelationship', definition: 'varchar(100) NULL' },
    { name: 'emergencyContactPhone', definition: 'varchar(50) NULL' },
    { name: 'bankName', definition: 'varchar(255) NULL' },
    { name: 'bankBranch', definition: 'varchar(255) NULL' },
    { name: 'nhifNumber', definition: 'varchar(50) NULL' },
    { name: 'nssfNumber', definition: 'varchar(50) NULL' },
    { name: 'organizationId', definition: 'varchar(64) NULL' },
  ],
  leaverequests: [
    { name: 'organizationId', definition: 'varchar(64) NULL' },
  ],
  attendance: [
    { name: 'organizationId', definition: 'varchar(64) NULL' },
  ],
  employeebenefits: [
    { name: 'employerCost', definition: 'int NULL' },
    { name: 'notes', definition: 'text NULL' },
  ],
  payrolldetails: [
    { name: 'payrollId', definition: 'varchar(64) NULL' },
    { name: 'itemType', definition: 'varchar(50) NULL' },
    { name: 'itemId', definition: 'varchar(64) NULL' },
    { name: 'description', definition: 'varchar(255) NULL' },
    { name: 'amount', definition: 'int NOT NULL DEFAULT 0' },
    { name: 'isDeduction', definition: 'tinyint NOT NULL DEFAULT 0' },
    { name: 'lineNumber', definition: 'int NULL' },
    { name: 'componentType', definition: 'varchar(100) NULL' },
    { name: 'component', definition: 'varchar(255) NULL' },
    { name: 'notes', definition: 'text NULL' },
  ],
  notifications: [
    {
      name: 'deliveryStatus',
      definition: "enum('pending','sent','failed') NOT NULL DEFAULT 'pending'",
    },
    {
      name: 'deliveryDate',
      definition: 'timestamp NULL',
    },
    {
      name: 'status',
      definition: "enum('active','archived') NOT NULL DEFAULT 'active'",
    },
  ],
  staffChatMessages: [
    { name: 'userId', definition: 'varchar(64) NULL' },
    { name: 'userName', definition: 'varchar(255) NULL' },
    { name: 'content', definition: 'text NULL' },
    { name: 'emoji', definition: 'varchar(10) NULL' },
    { name: 'replyToId', definition: 'varchar(64) NULL' },
    { name: 'replyToUser', definition: 'varchar(255) NULL' },
    { name: 'fileUrl', definition: 'varchar(500) NULL' },
    { name: 'fileName', definition: 'varchar(255) NULL' },
    { name: 'fileType', definition: 'varchar(50) NULL' },
    { name: 'isEdited', definition: 'tinyint NOT NULL DEFAULT 0' },
    { name: 'createdAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
    { name: 'updatedAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
    { name: 'encryptedKeys', definition: 'text NULL' },
    { name: 'encryptionNonce', definition: 'varchar(64) NULL' },
    { name: 'encryptionVersion', definition: 'varchar(10) NULL' },
  ],
  documents: [
    { name: 'linkedInvoiceId', definition: 'varchar(64) NULL' },
  ],
  departments: [
    {
      name: 'defaultRole',
      definition: 'varchar(100) NULL',
    },
    {
      name: 'organizationId',
      definition: 'varchar(64) NULL',
    },
    { name: 'description', definition: 'text NULL' },
    { name: 'headId', definition: 'varchar(64) NULL' },
    { name: 'budget', definition: 'int NULL' },
    { name: 'salaryRangeMin', definition: 'int NULL' },
    { name: 'salaryRangeMax', definition: 'int NULL' },
    { name: 'status', definition: "varchar(20) NULL DEFAULT 'active'" },
    { name: 'createdBy', definition: 'varchar(64) NULL' },
    { name: 'createdAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
    { name: 'updatedAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
  ],
  jobGroups: [
    { name: 'organizationId', definition: 'varchar(64) NULL' },
    { name: 'managerId', definition: 'varchar(64) NULL' },
    { name: 'minimumGrossSalary', definition: 'int NULL' },
    { name: 'maximumGrossSalary', definition: 'int NULL' },
    { name: 'defaultBasicSalary', definition: 'int NULL' },
    { name: 'defaultAnnualLeaveDays', definition: 'int NOT NULL DEFAULT 21' },
    { name: 'defaultAllowances', definition: 'text NULL' },
    { name: 'defaultDeductions', definition: 'text NULL' },
    { name: 'defaultBenefits', definition: 'text NULL' },
    { name: 'description', definition: 'text NULL' },
    { name: 'isActive', definition: 'tinyint NOT NULL DEFAULT 1' },
    { name: 'createdAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
    { name: 'updatedAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
  ],
  clients: [
    { name: 'organizationId', definition: 'varchar(64) NULL' },
    { name: 'secondaryPhone', definition: 'varchar(50) NULL' },
    { name: 'postalCode', definition: 'varchar(20) NULL' },
    { name: 'taxId', definition: 'varchar(100) NULL' },
    { name: 'website', definition: 'varchar(255) NULL' },
    { name: 'industry', definition: 'varchar(100) NULL' },
    { name: 'category', definition: 'varchar(100) NULL' },
    { name: 'status', definition: "enum('active','inactive','prospect','archived') NOT NULL DEFAULT 'active'" },
    { name: 'assignedTo', definition: 'varchar(64) NULL' },
    { name: 'notes', definition: 'text NULL' },
    { name: 'createdBy', definition: 'varchar(64) NULL' },
    { name: 'createdAt', definition: 'timestamp NULL' },
    { name: 'updatedAt', definition: 'timestamp NULL' },
    { name: 'businessType', definition: 'varchar(100) NULL' },
    { name: 'registrationNumber', definition: 'varchar(100) NULL' },
    { name: 'bankName', definition: 'varchar(255) NULL' },
    { name: 'bankCode', definition: 'varchar(50) NULL' },
    { name: 'branch', definition: 'varchar(100) NULL' },
    { name: 'bankAccountNumber', definition: 'varchar(100) NULL' },
    { name: 'creditLimit', definition: 'int NULL' },
    { name: 'paymentTerms', definition: 'varchar(100) NULL' },
    { name: 'numberOfEmployees', definition: 'int NULL' },
    { name: 'yearEstablished', definition: 'int NULL' },
    { name: 'businessLicense', definition: 'varchar(255) NULL' },
    { name: 'leadSource', definition: 'varchar(100) NULL' },
    { name: 'currency', definition: 'varchar(10) NULL' },
  ],
  expenses: [
    { name: 'organizationId', definition: 'varchar(64) NULL' },
    { name: 'expenseNumber', definition: 'varchar(100) NULL' },
    { name: 'budgetAllocationId', definition: 'varchar(64) NULL' },
    { name: 'approvedBy', definition: 'varchar(64) NULL' },
    { name: 'approvedAt', definition: 'datetime NULL' },
    { name: 'chartOfAccountId', definition: 'varchar(64) NULL' },
  ],
  budgetallocations: [
    { name: 'accountId', definition: 'varchar(64) NULL' },
  ],
  recurringexpenses: [
    { name: 'organizationId', definition: 'varchar(64) NULL' },
    { name: 'chartOfAccountId', definition: 'varchar(64) NULL' },
  ],
  projects: [
    { name: 'projectNumber', definition: 'varchar(100) NULL' },
    { name: 'actualStartDate', definition: 'datetime NULL' },
    { name: 'actualEndDate', definition: 'datetime NULL' },
    { name: 'actualCost', definition: 'int NULL DEFAULT 0' },
    { name: 'progress', definition: 'int NULL DEFAULT 0' },
    { name: 'projectColor', definition: "varchar(50) NULL DEFAULT 'primary'" },
    { name: 'teamSize', definition: 'int NULL DEFAULT 1' },
    { name: 'projectRating', definition: 'int NULL DEFAULT 0' },
    { name: 'coverImageUrl', definition: 'text NULL' },
    { name: 'projectManager', definition: 'varchar(64) NULL' },
    { name: 'assignedTo', definition: 'varchar(64) NULL' },
    { name: 'organizationId', definition: 'varchar(64) NULL' },
    { name: 'category', definition: 'varchar(100) NULL' },
    { name: 'tags', definition: 'text NULL' },
    { name: 'notes', definition: 'text NULL' },
  ],
  projecttasks: [
    { name: 'clientId', definition: 'varchar(64) NULL' },
    { name: 'tags', definition: 'text NULL' },
    { name: 'targetDate', definition: 'datetime NULL' },
    { name: 'billable', definition: 'tinyint NOT NULL DEFAULT 1' },
    { name: 'visibleToClient', definition: 'tinyint NOT NULL DEFAULT 1' },
  ],
  onboardingchecklists: [
    { name: 'templateId', definition: 'varchar(64) NULL' },
    { name: 'type', definition: "enum('onboarding','offboarding') NULL" },
    { name: 'assignedTo', definition: 'varchar(64) NULL' },
    { name: 'createdBy', definition: 'varchar(64) NULL' },
  ],
  onboardingtasks: [
    { name: 'templateId', definition: 'varchar(64) NULL' },
    { name: 'title', definition: 'varchar(255) NULL' },
    { name: 'completedAt', definition: 'datetime NULL' },
    { name: 'isRequired', definition: 'tinyint NOT NULL DEFAULT 1' },
    { name: 'sortOrder', definition: 'int NOT NULL DEFAULT 0' },
  ],
  trainingenrollments: [
    { name: 'programId', definition: 'varchar(64) NULL' },
    { name: 'enrolledAt', definition: 'datetime NULL' },
    { name: 'enrolledBy', definition: 'varchar(64) NULL' },
    { name: 'certificate', definition: 'varchar(500) NULL' },
    { name: 'completedAt', definition: 'datetime NULL' },
  ],
  trainingprograms: [
    { name: 'organizationId', definition: 'varchar(64) NULL' },
    { name: 'name', definition: 'varchar(200) NULL' },
    { name: 'description', definition: 'text NULL' },
    { name: 'category', definition: 'varchar(100) NULL' },
    { name: 'trainer', definition: 'varchar(200) NULL' },
    { name: 'startDate', definition: 'date NULL' },
    { name: 'endDate', definition: 'date NULL' },
    { name: 'maxParticipants', definition: 'int NULL' },
    { name: 'cost', definition: 'int NULL DEFAULT 0' },
    { name: 'location', definition: 'varchar(200) NULL' },
    { name: 'isOnline', definition: 'tinyint NOT NULL DEFAULT 0' },
    { name: 'isMandatory', definition: 'tinyint NOT NULL DEFAULT 0' },
    { name: 'status', definition: "enum('active','completed','cancelled','draft') NOT NULL DEFAULT 'active'" },
    { name: 'createdBy', definition: 'varchar(64) NULL' },
    { name: 'createdAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
    { name: 'updatedAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP' },
  ],
  onboardingtemplates: [
    { name: 'organizationId', definition: 'varchar(64) NULL' },
    { name: 'name', definition: 'varchar(255) NULL' },
    { name: 'description', definition: 'text NULL' },
    { name: 'type', definition: "enum('onboarding','offboarding') NULL" },
    { name: 'createdBy', definition: 'varchar(64) NULL' },
    { name: 'createdAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
    { name: 'updatedAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP' },
  ],
  // Organization isolation columns (multi-tenant support)
  payments: [
    {
      name: 'organizationId',
      definition: 'varchar(64) NULL',
    },
    { name: 'accountId', definition: 'varchar(64) NULL' },
    { name: 'chartOfAccountType', definition: "enum('debit','credit') NULL DEFAULT 'debit'" },
    { name: 'chartOfAccountId', definition: 'varchar(64) NULL' },
  ],
  receipts: [
    {
      name: 'organizationId',
      definition: 'varchar(64) NULL',
    },
    { name: 'subtotal', definition: 'int NOT NULL DEFAULT 0' },
    { name: 'taxAmount', definition: 'int NOT NULL DEFAULT 0' },
    { name: 'discountAmount', definition: 'int NOT NULL DEFAULT 0' },
    { name: 'status', definition: "enum('draft','issued','void') NOT NULL DEFAULT 'issued'" },
    { name: 'approvedBy', definition: 'varchar(64) NULL' },
    { name: 'approvedAt', definition: 'datetime NULL' },
  ],
  estimates: [
    {
      name: 'organizationId',
      definition: 'varchar(64) NULL',
    },
    {
      name: 'projectId',
      definition: 'varchar(64) NULL',
    },
    {
      name: 'category',
      definition: 'varchar(100) NULL',
    },
  ],
  serviceinvoiceitems: [
    {
      name: 'serviceId',
      definition: 'varchar(64) NULL',
    },
  ],
  quotations: [
    {
      name: 'organizationId',
      definition: 'varchar(64) NULL',
    },
  ],
  contacts: [
    {
      name: 'organizationId',
      definition: 'varchar(64) NULL',
    },
  ],
  products: [
    {
      name: 'organizationId',
      definition: 'varchar(64) NULL',
    },
    { name: 'supplier', definition: 'varchar(255) NULL' },
    { name: 'reorderLevel', definition: 'int NULL' },
    { name: 'reorderQuantity', definition: 'int NULL' },
    { name: 'lastRestockDate', definition: 'timestamp NULL' },
    { name: 'maxStockLevel', definition: 'int NULL' },
    { name: 'location', definition: 'varchar(255) NULL' },
    { name: 'barcode', definition: 'varchar(100) NULL' },
    { name: 'batchNumber', definition: 'varchar(100) NULL' },
    { name: 'manufacturingDate', definition: 'varchar(50) NULL' },
    { name: 'expiryDate', definition: 'varchar(50) NULL' },
    { name: 'warrantyMonths', definition: 'int NULL DEFAULT 0' },
    { name: 'hsCode', definition: 'varchar(50) NULL' },
    { name: 'weight', definition: 'varchar(20) NULL' },
    { name: 'weightUnit', definition: "varchar(20) NULL DEFAULT 'kg'" },
    { name: 'warehouseLocation', definition: 'varchar(255) NULL' },
  ],
  services: [
    {
      name: 'organizationId',
      definition: 'varchar(64) NULL',
    },
    { name: 'name', definition: 'varchar(255) NULL' },
    { name: 'description', definition: 'text NULL' },
    { name: 'category', definition: 'varchar(100) NULL' },
    { name: 'hourlyRate', definition: 'int NULL' },
    { name: 'fixedPrice', definition: 'int NULL' },
    { name: 'unit', definition: "varchar(50) NULL DEFAULT 'hour'" },
    { name: 'taxRate', definition: 'int NULL DEFAULT 0' },
    { name: 'deliverables', definition: 'text NULL' },
    { name: 'isActive', definition: 'tinyint NOT NULL DEFAULT 1' },
    { name: 'createdBy', definition: 'varchar(64) NULL' },
    { name: 'createdAt', definition: 'timestamp NULL' },
    { name: 'updatedAt', definition: 'timestamp NULL' },
  ],
  suppliers: [
    { name: 'organizationId', definition: 'varchar(64) NULL' },
    { name: 'supplierNumber', definition: 'varchar(50) NULL UNIQUE' },
    { name: 'registrationNumber', definition: 'varchar(100) NULL' },
    { name: 'taxId', definition: 'varchar(100) NULL' },
    { name: 'contactPerson', definition: 'varchar(255) NULL' },
    { name: 'contactTitle', definition: 'varchar(100) NULL' },
    { name: 'alternatePhone', definition: 'varchar(50) NULL' },
    { name: 'website', definition: 'varchar(255) NULL' },
    { name: 'address', definition: 'text NULL' },
    { name: 'city', definition: 'varchar(100) NULL' },
    { name: 'country', definition: 'varchar(100) NULL' },
    { name: 'postalCode', definition: 'varchar(20) NULL' },
    { name: 'bankName', definition: 'varchar(255) NULL' },
    { name: 'bankBranch', definition: 'varchar(255) NULL' },
    { name: 'accountNumber', definition: 'varchar(100) NULL' },
    { name: 'accountName', definition: 'varchar(255) NULL' },
    { name: 'paymentTerms', definition: 'varchar(100) NULL' },
    { name: 'paymentMethods', definition: 'varchar(255) NULL' },
    { name: 'categories', definition: 'varchar(500) NULL' },
    { name: 'qualificationStatus', definition: "enum('pending','pre_qualified','qualified','rejected','inactive') NOT NULL DEFAULT 'pending'" },
    { name: 'qualificationDate', definition: 'datetime NULL' },
    { name: 'certifications', definition: 'varchar(500) NULL' },
    { name: 'qualityRating', definition: 'int NULL DEFAULT 0' },
    { name: 'deliveryRating', definition: 'int NULL DEFAULT 0' },
    { name: 'priceCompetitiveness', definition: 'int NULL DEFAULT 0' },
    { name: 'averageRating', definition: 'int NULL DEFAULT 0' },
    { name: 'totalOrders', definition: 'int NULL DEFAULT 0' },
    { name: 'totalSpent', definition: 'int NULL DEFAULT 0' },
    { name: 'lastOrderDate', definition: 'datetime NULL' },
    { name: 'isActive', definition: 'tinyint NOT NULL DEFAULT 1' },
    { name: 'accountManagerId', definition: 'varchar(64) NULL' },
    { name: 'notes', definition: 'text NULL' },
    { name: 'createdBy', definition: 'varchar(64) NULL' },
    { name: 'createdAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
    { name: 'updatedAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
  ],
  opportunities: [
    {
      name: 'organizationId',
      definition: 'varchar(64) NULL',
    },
    { name: 'category', definition: 'varchar(100) NULL' },
  ],
  projectBudgets: [
    {
      name: 'organizationId',
      definition: 'varchar(64) NULL',
    },
  ],
  departmentBudgets: [
    {
      name: 'organizationId',
      definition: 'varchar(64) NULL',
    },
  ],
  creditNotes: [
    {
      name: 'organizationId',
      definition: 'varchar(64) NULL',
    },
  ],
  warranties: [
    {
      name: 'organizationId',
      definition: 'varchar(64) NULL',
    },
  ],
  lpos: [
    {
      name: 'organizationId',
      definition: 'varchar(64) NULL',
    },
  ],
  grnRecords: [
    {
      name: 'organizationId',
      definition: 'varchar(64) NULL',
    },
  ],
  serviceInvoices: [
    {
      name: 'organizationId',
      definition: 'varchar(64) NULL',
    },
  ],
  serviceTemplates: [
    {
      name: 'organizationId',
      definition: 'varchar(64) NULL',
    },
  ],
  emailTemplates: [
    {
      name: 'organizationId',
      definition: 'varchar(64) NULL',
    },
    {
      name: 'plainTextContent',
      definition: 'text NULL',
    },
    {
      name: 'attachments',
      definition: 'json NULL',
    },
    {
      name: 'isDefault',
      definition: 'tinyint NOT NULL DEFAULT 0',
    },
    {
      name: 'isSystem',
      definition: 'tinyint NOT NULL DEFAULT 0',
    },
  ],
  emailQueue: [
    {
      name: 'organizationId',
      definition: 'varchar(64) NULL',
    },
  ],
  paymentTriggers: [
    { name: 'invoiceId', definition: 'varchar(64) NULL' },
    { name: 'metadata', definition: 'json NULL' },
  ],
  proposalTemplates: [
    {
      name: 'organizationId',
      definition: 'varchar(64) NULL',
    },
  ],
  contractTemplates: [
    {
      name: 'organizationId',
      definition: 'varchar(64) NULL',
    },
  ],
  payroll: [
    { name: 'employeeId', definition: 'varchar(64) NOT NULL' },
    { name: 'payPeriodStart', definition: 'datetime NOT NULL' },
    { name: 'payPeriodEnd', definition: 'datetime NOT NULL' },
    { name: 'basicSalary', definition: 'int NOT NULL' },
    { name: 'allowances', definition: 'int NULL DEFAULT 0' },
    { name: 'deductions', definition: 'int NULL DEFAULT 0' },
    { name: 'tax', definition: 'int NULL DEFAULT 0' },
    { name: 'netSalary', definition: 'int NOT NULL' },
    { name: 'status', definition: "enum('draft','processed','paid') NOT NULL DEFAULT 'draft'" },
    { name: 'paymentDate', definition: 'datetime NULL' },
    { name: 'paymentMethod', definition: 'varchar(50) NULL' },
    { name: 'notes', definition: 'text NULL' },
    { name: 'createdBy', definition: 'varchar(64) NULL' },
    { name: 'createdAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
    { name: 'updatedAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
  ],
  scheduledJobs: [
    {
      name: 'organizationId',
      definition: 'varchar(64) NULL',
    },
  ],
  partner_profiles: [
    { name: 'id', definition: 'varchar(64) NULL' },
    { name: 'userId', definition: 'varchar(64) NULL' },
    { name: 'name', definition: "varchar(255) NOT NULL DEFAULT ''" },
    { name: 'email', definition: "varchar(320) NOT NULL DEFAULT ''" },
    { name: 'company', definition: 'varchar(255) NULL' },
    { name: 'phone', definition: 'varchar(50) NULL' },
    { name: 'website', definition: 'varchar(500) NULL' },
    { name: 'partnerType', definition: "varchar(30) NOT NULL DEFAULT 'affiliate'" },
    { name: 'status', definition: "varchar(30) NOT NULL DEFAULT 'pending'" },
    { name: 'referralCode', definition: "varchar(80) NOT NULL DEFAULT ''" },
    { name: 'commissionRate', definition: 'decimal(5,2) NULL DEFAULT 15' },
    { name: 'notes', definition: 'text NULL' },
    { name: 'createdAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
    { name: 'updatedAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
  ],
  partner_referrals: [
    { name: 'id', definition: 'varchar(64) NULL' },
    { name: 'partnerId', definition: "varchar(64) NOT NULL DEFAULT ''" },
    { name: 'referredName', definition: 'varchar(255) NULL' },
    { name: 'referredEmail', definition: "varchar(320) NOT NULL DEFAULT ''" },
    { name: 'organizationId', definition: 'varchar(64) NULL' },
    { name: 'source', definition: "varchar(100) NULL DEFAULT 'partner'" },
    { name: 'status', definition: "varchar(30) NOT NULL DEFAULT 'submitted'" },
    { name: 'convertedAt', definition: 'timestamp NULL' },
    { name: 'notes', definition: 'text NULL' },
    { name: 'createdAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
    { name: 'updatedAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
  ],
  partner_commissions: [
    { name: 'id', definition: 'varchar(64) NULL' },
    { name: 'partnerId', definition: "varchar(64) NOT NULL DEFAULT ''" },
    { name: 'referralId', definition: 'varchar(64) NULL' },
    { name: 'dealId', definition: 'varchar(64) NULL' },
    { name: 'amount', definition: 'decimal(15,2) NOT NULL DEFAULT 0' },
    { name: 'currency', definition: "varchar(10) NOT NULL DEFAULT 'KES'" },
    { name: 'status', definition: "varchar(30) NOT NULL DEFAULT 'pending'" },
    { name: 'earnedAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
    { name: 'payableAt', definition: 'timestamp NULL' },
    { name: 'paidAt', definition: 'timestamp NULL' },
    { name: 'notes', definition: 'text NULL' },
    { name: 'createdAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
  ],
  partner_payouts: [
    { name: 'id', definition: 'varchar(64) NULL' },
    { name: 'partnerId', definition: "varchar(64) NOT NULL DEFAULT ''" },
    { name: 'amount', definition: 'decimal(15,2) NOT NULL DEFAULT 0' },
    { name: 'currency', definition: "varchar(10) NOT NULL DEFAULT 'KES'" },
    { name: 'method', definition: "varchar(50) NOT NULL DEFAULT 'bank'" },
    { name: 'reference', definition: 'varchar(255) NULL' },
    { name: 'status', definition: "varchar(30) NOT NULL DEFAULT 'requested'" },
    { name: 'requestedAt', definition: 'timestamp NULL DEFAULT CURRENT_TIMESTAMP' },
    { name: 'processedAt', definition: 'timestamp NULL' },
    { name: 'notes', definition: 'text NULL' },
  ],
};

const legacyTableCatalog: Record<string, LegacyTableDefinition> = {
  settings: {
    name: 'settings',
    createSql: `CREATE TABLE IF NOT EXISTS settings (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      \`key\` VARCHAR(100) NOT NULL,
      value LONGTEXT NULL,
      category VARCHAR(100) NULL,
      description TEXT NULL,
      updatedBy VARCHAR(64) NULL,
      updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX key_idx (\`key\`),
      INDEX category_idx (category)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  organizationSettings: {
    name: 'organizationSettings',
    createSql: `CREATE TABLE IF NOT EXISTS organizationSettings (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      organizationId VARCHAR(64) NOT NULL,
      \`key\` VARCHAR(100) NOT NULL,
      value LONGTEXT NULL,
      category VARCHAR(100) NOT NULL,
      description TEXT NULL,
      updatedBy VARCHAR(64) NULL,
      updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
      UNIQUE KEY org_settings_scope_key_idx (organizationId, category, \`key\`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  budgetAllocations: {
    name: 'budgetAllocations',
    createSql: `CREATE TABLE IF NOT EXISTS budgetAllocations (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      budgetId VARCHAR(64) NOT NULL,
      accountId VARCHAR(64) NULL,
      categoryName VARCHAR(255) NOT NULL,
      allocatedAmount INT NOT NULL,
      spentAmount INT NOT NULL DEFAULT 0,
      notes TEXT NULL,
      createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX allocation_budget_idx (budgetId)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  onboardingChecklists: {
    name: 'onboardingChecklists',
    createSql: `CREATE TABLE IF NOT EXISTS onboardingChecklists (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      organizationId VARCHAR(64) NOT NULL,
      employeeId VARCHAR(64) NOT NULL,
      jobGroupId VARCHAR(64) NULL,
      templateId VARCHAR(64) NULL,
      type ENUM('onboarding','offboarding') NULL,
      assignedTo VARCHAR(64) NULL,
      startDate DATETIME NOT NULL,
      probationEndDate DATETIME NULL,
      overallProgress INT NULL DEFAULT 0,
      status ENUM('in_progress','completed','paused') NOT NULL DEFAULT 'in_progress',
      completedDate DATETIME NULL,
      notes TEXT NULL,
      createdBy VARCHAR(64) NULL,
      createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  onboardingTasks: {
    name: 'onboardingTasks',
    createSql: `CREATE TABLE IF NOT EXISTS onboardingTasks (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      organizationId VARCHAR(64) NOT NULL,
      checklistId VARCHAR(64) NOT NULL,
      templateId VARCHAR(64) NULL,
      title VARCHAR(255) NULL,
      taskName VARCHAR(255) NOT NULL,
      category ENUM('it_setup','paperwork','training','introduction','other') NOT NULL DEFAULT 'other',
      description TEXT NULL,
      assignedTo VARCHAR(64) NULL,
      dueDate DATETIME NULL,
      completedDate DATETIME NULL,
      completedAt DATETIME NULL,
      completedBy VARCHAR(64) NULL,
      status ENUM('pending','in_progress','completed','skipped') NOT NULL DEFAULT 'pending',
      priority ENUM('low','medium','high') NOT NULL DEFAULT 'medium',
      isRequired TINYINT NOT NULL DEFAULT 1,
      sortOrder INT NOT NULL DEFAULT 0,
      notes TEXT NULL,
      createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  onboardingTemplates: {
    name: 'onboardingTemplates',
    createSql: `CREATE TABLE IF NOT EXISTS onboardingTemplates (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      organizationId VARCHAR(64) NULL,
      name VARCHAR(255) NOT NULL,
      description TEXT NULL,
      type ENUM('onboarding','offboarding') NOT NULL,
      createdBy VARCHAR(64) NULL,
      createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX idx_onboarding_templates_org (organizationId),
      INDEX idx_onboarding_templates_type (type)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  trainingEnrollments: {
    name: 'trainingEnrollments',
    createSql: `CREATE TABLE IF NOT EXISTS trainingEnrollments (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      organizationId VARCHAR(64) NOT NULL,
      courseId VARCHAR(64) NULL,
      programId VARCHAR(64) NULL,
      employeeId VARCHAR(64) NOT NULL,
      enrollmentDate DATETIME NULL,
      enrolledAt DATETIME NULL,
      enrolledBy VARCHAR(64) NULL,
      status ENUM('enrolled','in_progress','completed','dropped','passed','failed') NOT NULL DEFAULT 'enrolled',
      attendancePercentage INT NULL DEFAULT 0,
      score INT NULL DEFAULT 0,
      certificateIssued TINYINT NULL DEFAULT 0,
      certificate VARCHAR(500) NULL,
      certificateDate DATETIME NULL,
      certificateUrl VARCHAR(500) NULL,
      completedAt DATETIME NULL,
      feedback TEXT NULL,
      createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  trainingPrograms: {
    name: 'trainingPrograms',
    createSql: `CREATE TABLE IF NOT EXISTS trainingPrograms (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      organizationId VARCHAR(64) NULL,
      name VARCHAR(200) NOT NULL,
      description TEXT NULL,
      category VARCHAR(100) NULL,
      trainer VARCHAR(200) NULL,
      startDate DATE NULL,
      endDate DATE NULL,
      maxParticipants INT NULL,
      cost INT NULL DEFAULT 0,
      location VARCHAR(200) NULL,
      isOnline TINYINT NOT NULL DEFAULT 0,
      isMandatory TINYINT NOT NULL DEFAULT 0,
      status ENUM('active','completed','cancelled','draft') NOT NULL DEFAULT 'active',
      createdBy VARCHAR(64) NULL,
      createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX idx_training_programs_org (organizationId),
      INDEX idx_training_programs_status (status),
      INDEX idx_training_programs_start (startDate)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  eSignatureRequests: {
    name: 'eSignatureRequests',
    createSql: `CREATE TABLE IF NOT EXISTS eSignatureRequests (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      organizationId VARCHAR(64) NULL,
      title VARCHAR(255) NOT NULL,
      documentContent LONGTEXT NOT NULL,
      signerName VARCHAR(255) NOT NULL,
      signerEmail VARCHAR(320) NOT NULL,
      signingToken VARCHAR(128) NOT NULL UNIQUE,
      status ENUM('pending','signed','declined','expired') NOT NULL DEFAULT 'pending',
      signatureData LONGTEXT NULL,
      signedAt TIMESTAMP NULL,
      expiresAt TIMESTAMP NULL,
      createdBy VARCHAR(64) NOT NULL,
      createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
  jobGroups: {
    name: 'jobGroups',
    createSql: `CREATE TABLE IF NOT EXISTS jobGroups (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      organizationId VARCHAR(64) NULL,
      name VARCHAR(100) NOT NULL,
      managerId VARCHAR(64) NULL,
      minimumGrossSalary INT NULL,
      maximumGrossSalary INT NULL,
      description TEXT NULL,
      isActive TINYINT NOT NULL DEFAULT 1,
      createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX job_group_org_idx (organizationId),
      INDEX job_group_manager_idx (managerId),
      INDEX job_group_name_idx (name),
      INDEX is_active_idx (isActive)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
  customRoles: {
    name: 'customRoles',
    createSql: `CREATE TABLE IF NOT EXISTS customRoles (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      organizationId VARCHAR(64) NULL,
      name VARCHAR(100) NOT NULL,
      displayName VARCHAR(255) NOT NULL,
      description TEXT NULL,
      permissions TEXT NULL,
      baseRole VARCHAR(50) DEFAULT 'staff',
      isAdvanced TINYINT NOT NULL DEFAULT 0,
      isSystem TINYINT NOT NULL DEFAULT 0,
      isActive TINYINT NOT NULL DEFAULT 1,
      createdBy VARCHAR(64) NULL,
      createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
      INDEX idx_customRoles_orgId (organizationId),
      INDEX idx_customRoles_name (name),
      INDEX idx_customRoles_active (isActive)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
  payroll: {
    name: 'payroll',
    createSql: `CREATE TABLE IF NOT EXISTS payroll (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      employeeId VARCHAR(64) NOT NULL,
      payPeriodStart DATETIME NOT NULL,
      payPeriodEnd DATETIME NOT NULL,
      basicSalary INT NOT NULL,
      allowances INT NULL DEFAULT 0,
      deductions INT NULL DEFAULT 0,
      tax INT NULL DEFAULT 0,
      netSalary INT NOT NULL,
      status ENUM('draft','processed','paid') NOT NULL DEFAULT 'draft',
      paymentDate DATETIME NULL,
      paymentMethod VARCHAR(50) NULL,
      notes TEXT NULL,
      createdBy VARCHAR(64) NULL,
      createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX idx_payroll_employee (employeeId),
      INDEX idx_payroll_period (payPeriodStart, payPeriodEnd),
      INDEX idx_payroll_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
  paymentTriggers: {
    name: 'paymentTriggers',
    createSql: `CREATE TABLE IF NOT EXISTS paymentTriggers (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      organizationId VARCHAR(64) NOT NULL,
      invoiceId VARCHAR(64) NULL,
      triggerType VARCHAR(100) NOT NULL,
      triggerDate TIMESTAMP NULL,
      isActive TINYINT NOT NULL DEFAULT 1,
      status VARCHAR(50) NOT NULL DEFAULT 'pending',
      actionType VARCHAR(100) NOT NULL DEFAULT 'invoice_generate',
      amount DECIMAL(10, 2) NULL,
      description TEXT NULL,
      metadata JSON NULL,
      retryCount INT NOT NULL DEFAULT 0,
      lastRetryAt TIMESTAMP NULL,
      nextRetryAt TIMESTAMP NULL,
      completedAt TIMESTAMP NULL,
      errorMessage TEXT NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX idx_payment_triggers_org (organizationId),
      INDEX idx_payment_triggers_date (triggerDate),
      INDEX idx_payment_triggers_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
  emailTemplates: {
    name: 'emailTemplates',
    createSql: `CREATE TABLE IF NOT EXISTS emailTemplates (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      subject VARCHAR(500) NOT NULL,
      htmlContent LONGTEXT NOT NULL,
      plainTextContent TEXT NULL,
      variables JSON NULL,
      category VARCHAR(100) NOT NULL DEFAULT 'general',
      attachments JSON NULL,
      isDefault TINYINT NOT NULL DEFAULT 0,
      isSystem TINYINT NOT NULL DEFAULT 0,
      createdBy VARCHAR(64) NULL,
      organizationId VARCHAR(64) NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX idx_email_templates_org (organizationId),
      INDEX idx_email_templates_category (category)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
  contractTemplates: {
    name: 'contractTemplates',
    createSql: `CREATE TABLE IF NOT EXISTS contractTemplates (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      title VARCHAR(255) NOT NULL,
      content LONGTEXT NOT NULL,
      createdBy VARCHAR(64) NULL,
      organizationId VARCHAR(64) NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX idx_contract_templates_org (organizationId),
      INDEX idx_contract_templates_created (createdAt)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
  proposalTemplates: {
    name: 'proposalTemplates',
    createSql: `CREATE TABLE IF NOT EXISTS proposalTemplates (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      title VARCHAR(255) NOT NULL,
      content LONGTEXT NOT NULL,
      createdBy VARCHAR(64) NULL,
      organizationId VARCHAR(64) NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX idx_proposal_templates_org (organizationId),
      INDEX idx_proposal_templates_created (createdAt)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  },
  scheduledJobs: {
    name: 'scheduledJobs',
    createSql: `CREATE TABLE IF NOT EXISTS scheduledJobs (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      organizationId VARCHAR(64) NOT NULL,
      jobName VARCHAR(255) NOT NULL,
      jobType VARCHAR(100) NOT NULL,
      schedule VARCHAR(255) NOT NULL,
      description TEXT NULL,
      cronExpression VARCHAR(255) NULL,
      handler TEXT NULL,
      status ENUM('active','inactive','paused') NOT NULL DEFAULT 'active',
      isActive TINYINT NOT NULL DEFAULT 1,
      isManualOnly TINYINT NOT NULL DEFAULT 0,
      lastRun TIMESTAMP NULL,
      nextRun TIMESTAMP NULL,
      lastExecutedAt TIMESTAMP NULL,
      nextExecutionAt TIMESTAMP NULL,
      lastRunAt TIMESTAMP NULL,
      lastRunStatus ENUM('success','failed','partial','timeout') NULL,
      lastRunDuration INT NULL,
      nextScheduledRun TIMESTAMP NULL,
      lastFailureReason TEXT NULL,
      failureCount INT NOT NULL DEFAULT 0,
      timezone VARCHAR(100) NULL DEFAULT 'UTC',
      createdBy VARCHAR(64) NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX idx_scheduled_jobs_org (organizationId),
      INDEX idx_scheduled_jobs_status (status),
      INDEX idx_scheduled_jobs_active (isActive)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  jobExecutionLogs: {
    name: 'jobExecutionLogs',
    createSql: `CREATE TABLE IF NOT EXISTS jobExecutionLogs (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      jobId VARCHAR(64) NOT NULL,
      status ENUM('pending','running','completed','failed','success','partial','timeout') NOT NULL DEFAULT 'pending',
      startTime TIMESTAMP NULL,
      startedAt TIMESTAMP NULL,
      completedAt TIMESTAMP NULL,
      executedAt TIMESTAMP NULL,
      endTime TIMESTAMP NULL,
      duration INT NULL,
      durationMs INT NULL,
      itemsProcessed INT NOT NULL DEFAULT 0,
      itemsFailed INT NOT NULL DEFAULT 0,
      itemsSkipped INT NOT NULL DEFAULT 0,
      errorMessage TEXT NULL,
      stdout LONGTEXT NULL,
      stderr LONGTEXT NULL,
      metadata JSON NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      INDEX idx_job_execution_logs_job_id (jobId),
      INDEX idx_job_execution_logs_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  jobAlertRules: {
    name: 'jobAlertRules',
    createSql: `CREATE TABLE IF NOT EXISTS jobAlertRules (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      jobId VARCHAR(64) NOT NULL,
      alertType ENUM('failure','timeout','performance') NOT NULL,
      threshold INT NULL,
      triggerCondition VARCHAR(100) NULL,
      failureThreshold INT NULL,
      durationThresholdMs INT NULL,
      notificationChannels JSON NULL,
      recipients JSON NULL,
      action VARCHAR(100) NULL,
      isActive TINYINT NOT NULL DEFAULT 1,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      INDEX idx_job_alert_rules_job_id (jobId),
      INDEX idx_job_alert_rules_active (isActive)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  jobAlertHistory: {
    name: 'jobAlertHistory',
    createSql: `CREATE TABLE IF NOT EXISTS jobAlertHistory (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      ruleId VARCHAR(64) NOT NULL,
      alertRuleId VARCHAR(64) NULL,
      alertMessage TEXT NULL,
      message TEXT NULL,
      sentAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      alert_sent_at TIMESTAMP NULL,
      recipients JSON NULL,
      INDEX idx_job_alert_history_rule_id (ruleId)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  jobHeartbeat: {
    name: 'jobHeartbeat',
    createSql: `CREATE TABLE IF NOT EXISTS jobHeartbeat (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      jobId VARCHAR(64) NOT NULL UNIQUE,
      lastHeartbeatAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      checkedAt TIMESTAMP NULL,
      expectedHeartbeatInterval INT NULL,
      isHealthy TINYINT NOT NULL DEFAULT 1,
      consecutiveFailures INT NOT NULL DEFAULT 0,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      INDEX idx_job_heartbeat_job_id (jobId),
      INDEX idx_job_heartbeat_healthy (isHealthy)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  integration_configs: {
    name: 'integration_configs',
    createSql: `CREATE TABLE IF NOT EXISTS integration_configs (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      provider VARCHAR(100) NOT NULL,
      name VARCHAR(200) NULL,
      service VARCHAR(100) NULL,
      integrationType VARCHAR(50) NULL,
      config TEXT NULL,
      status VARCHAR(20) DEFAULT 'inactive',
      isActive TINYINT NOT NULL DEFAULT 1,
      lastSync TIMESTAMP NULL,
      lastSyncAt TIMESTAMP NULL,
      createdBy VARCHAR(64) NOT NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      INDEX idx_ic_provider (provider),
      INDEX idx_ic_active (isActive),
      INDEX idx_ic_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  contacts: {
    name: 'contacts',
    createSql: `CREATE TABLE IF NOT EXISTS contacts (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      organizationId VARCHAR(64) NULL,
      clientId VARCHAR(64) NULL,
      salutation VARCHAR(20) NULL,
      firstName VARCHAR(100) NOT NULL,
      lastName VARCHAR(100) NOT NULL,
      email VARCHAR(320) NULL,
      phone VARCHAR(50) NULL,
      mobile VARCHAR(50) NULL,
      jobTitle VARCHAR(200) NULL,
      department VARCHAR(200) NULL,
      isPrimary TINYINT DEFAULT 0,
      notes TEXT NULL,
      address TEXT NULL,
      city VARCHAR(100) NULL,
      country VARCHAR(100) NULL,
      postalCode VARCHAR(20) NULL,
      linkedIn VARCHAR(500) NULL,
      createdBy VARCHAR(64) NOT NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      INDEX idx_contacts_client (clientId),
      INDEX idx_contacts_email (email)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  notes: {
    name: 'notes',
    createSql: `CREATE TABLE IF NOT EXISTS notes (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      title VARCHAR(300) NOT NULL,
      content TEXT NULL,
      category VARCHAR(100) NOT NULL DEFAULT 'General',
      pinned TINYINT NOT NULL DEFAULT 0,
      favorite TINYINT NOT NULL DEFAULT 0,
      createdBy VARCHAR(64) NOT NULL,
      organizationId VARCHAR(64) NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      INDEX idx_notes_created_by (createdBy),
      INDEX idx_notes_category (category)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  userTablePreferences: {
    name: 'userTablePreferences',
    createSql: `CREATE TABLE IF NOT EXISTS userTablePreferences (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      userId VARCHAR(64) NOT NULL,
      organizationId VARCHAR(64) NULL,
      tableName VARCHAR(100) NOT NULL,
      visibleColumns TEXT NULL,
      columnOrder TEXT NULL,
      pageSize INT DEFAULT 25,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      INDEX utp_user_table_idx (userId, tableName),
      INDEX utp_org_idx (organizationId)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  organizationMembers: {
    name: 'organizationMembers',
    createSql: `CREATE TABLE IF NOT EXISTS organizationMembers (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      organizationId VARCHAR(64) NOT NULL,
      userId VARCHAR(64) NOT NULL,
      role VARCHAR(50) NULL,
      status ENUM('active', 'inactive', 'invited', 'removed') NOT NULL DEFAULT 'active',
      isActive TINYINT NOT NULL DEFAULT 1,
      invitedBy VARCHAR(64) NULL,
      joinedAt DATETIME NULL,
      leftAt DATETIME NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      INDEX org_members_org_idx (organizationId),
      INDEX org_members_user_idx (userId),
      INDEX org_members_org_user_idx (organizationId, userId),
      INDEX org_members_status_idx (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  staffChatMessages: {
    name: 'staffChatMessages',
    createSql: `CREATE TABLE IF NOT EXISTS staffChatMessages (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      channelId VARCHAR(100) NOT NULL,
      userId VARCHAR(64) NOT NULL,
      userName VARCHAR(255) NOT NULL,
      content TEXT NOT NULL,
      emoji VARCHAR(10) NULL,
      replyToId VARCHAR(64) NULL,
      replyToUser VARCHAR(255) NULL,
      fileUrl VARCHAR(500) NULL,
      fileName VARCHAR(255) NULL,
      fileType VARCHAR(50) NULL,
      isEdited TINYINT NOT NULL DEFAULT 0,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      INDEX idx_channel_id (channelId),
      INDEX idx_user_id (userId),
      INDEX idx_created_at (createdAt)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  documents: {
    name: 'documents',
    createSql: `CREATE TABLE IF NOT EXISTS documents (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      organizationId VARCHAR(64) NULL,
      documentName VARCHAR(255) NOT NULL,
      documentType VARCHAR(50) NULL,
      fileUrl VARCHAR(500) NOT NULL,
      fileSize INT DEFAULT 0,
      mimeType VARCHAR(100) NULL,
      linkedEntityType VARCHAR(100) NULL,
      linkedEntityId VARCHAR(64) NULL,
      linkedClientId VARCHAR(64) NULL,
      linkedProjectId VARCHAR(64) NULL,
      linkedInvoiceId VARCHAR(64) NULL,
      uploadedBy VARCHAR(64) NOT NULL,
      currentVersion INT DEFAULT 1,
      status VARCHAR(20) DEFAULT 'active',
      expiryDate TIMESTAMP NULL,
      requiresSignature TINYINT DEFAULT 0,
      isSigned TINYINT DEFAULT 0,
      signedDate TIMESTAMP NULL,
      signedBy VARCHAR(64) NULL,
      tags TEXT NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  backup_history: {
    name: 'backup_history',
    createSql: `CREATE TABLE IF NOT EXISTS backup_history (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      name VARCHAR(200) NOT NULL,
      backupType VARCHAR(50) NOT NULL DEFAULT 'full',
      scope VARCHAR(50) NOT NULL DEFAULT 'full',
      scopeEntityId VARCHAR(64) NULL,
      status VARCHAR(50) NOT NULL DEFAULT 'pending',
      tablesList TEXT NULL,
      recordCount INT DEFAULT 0,
      sizeBytes INT DEFAULT 0,
      fileName VARCHAR(500) NULL,
      errorMessage TEXT NULL,
      completedAt TIMESTAMP NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      createdBy VARCHAR(64) NOT NULL,
      INDEX idx_bh_status (status),
      INDEX idx_bh_scope (scope),
      INDEX idx_bh_created (createdAt)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  systemHealth: {
    name: 'systemHealth',
    createSql: `CREATE TABLE IF NOT EXISTS systemHealth (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      organizationId VARCHAR(64) NULL,
      cpuUsage FLOAT NULL,
      cpuModel VARCHAR(255) NULL,
      cpuCores INT NULL,
      cpuSpeed VARCHAR(50) NULL,
      cpuTemperature FLOAT NULL,
      memoryUsage FLOAT NULL,
      memoryTotal FLOAT NULL,
      memoryAvailable FLOAT NULL,
      diskUsage FLOAT NULL,
      diskTotal FLOAT NULL,
      diskUsagePercent FLOAT NULL,
      status VARCHAR(50) DEFAULT 'healthy',
      systemPlatform VARCHAR(50) NULL,
      systemDistro VARCHAR(255) NULL,
      systemRelease VARCHAR(100) NULL,
      systemArch VARCHAR(50) NULL,
      systemManufacturer VARCHAR(255) NULL,
      systemUptime BIGINT NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      INDEX idx_created_at (createdAt)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  compliance_records: {
    name: 'compliance_records',
    createSql: `CREATE TABLE IF NOT EXISTS compliance_records (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      recordType VARCHAR(100) NOT NULL,
      standard VARCHAR(100) NULL,
      score INT DEFAULT 0,
      status VARCHAR(50) NOT NULL DEFAULT 'COMPLIANT',
      findings TEXT NULL,
      dataPayload TEXT NULL,
      createdBy VARCHAR(64) NOT NULL,
      createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX idx_cr_type (recordType),
      INDEX idx_cr_standard (standard)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  partner_profiles: {
    name: 'partner_profiles',
    createSql: `CREATE TABLE IF NOT EXISTS partner_profiles (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      userId VARCHAR(64) NULL,
      name VARCHAR(255) NOT NULL,
      email VARCHAR(320) NOT NULL,
      company VARCHAR(255) NULL,
      phone VARCHAR(50) NULL,
      website VARCHAR(500) NULL,
      partnerType VARCHAR(30) NOT NULL,
      status VARCHAR(30) NOT NULL DEFAULT 'pending',
      referralCode VARCHAR(80) NOT NULL,
      commissionRate DECIMAL(5,2) NULL DEFAULT 15,
      notes TEXT NULL,
      createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
      INDEX idx_partner_profiles_email (email),
      INDEX idx_partner_profiles_status (status),
      INDEX idx_partner_profiles_code (referralCode)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  partner_referrals: {
    name: 'partner_referrals',
    createSql: `CREATE TABLE IF NOT EXISTS partner_referrals (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      partnerId VARCHAR(64) NOT NULL,
      referredName VARCHAR(255) NULL,
      referredEmail VARCHAR(320) NOT NULL,
      organizationId VARCHAR(64) NULL,
      source VARCHAR(100) NULL DEFAULT 'partner',
      status VARCHAR(30) NOT NULL DEFAULT 'submitted',
      convertedAt TIMESTAMP NULL,
      notes TEXT NULL,
      createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
      INDEX idx_partner_referrals_partner (partnerId),
      INDEX idx_partner_referrals_email (referredEmail),
      INDEX idx_partner_referrals_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  partner_commissions: {
    name: 'partner_commissions',
    createSql: `CREATE TABLE IF NOT EXISTS partner_commissions (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      partnerId VARCHAR(64) NOT NULL,
      referralId VARCHAR(64) NULL,
      dealId VARCHAR(64) NULL,
      amount DECIMAL(15,2) NOT NULL,
      currency VARCHAR(10) NOT NULL DEFAULT 'KES',
      status VARCHAR(30) NOT NULL DEFAULT 'pending',
      earnedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
      payableAt TIMESTAMP NULL,
      paidAt TIMESTAMP NULL,
      notes TEXT NULL,
      createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
      INDEX idx_partner_commissions_partner (partnerId),
      INDEX idx_partner_commissions_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
  partner_payouts: {
    name: 'partner_payouts',
    createSql: `CREATE TABLE IF NOT EXISTS partner_payouts (
      id VARCHAR(64) NOT NULL PRIMARY KEY,
      partnerId VARCHAR(64) NOT NULL,
      amount DECIMAL(15,2) NOT NULL,
      currency VARCHAR(10) NOT NULL DEFAULT 'KES',
      method VARCHAR(50) NOT NULL,
      reference VARCHAR(255) NULL,
      status VARCHAR(30) NOT NULL DEFAULT 'requested',
      requestedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
      processedAt TIMESTAMP NULL,
      notes TEXT NULL,
      INDEX idx_partner_payouts_partner (partnerId),
      INDEX idx_partner_payouts_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  },
};

export function getMissingColumnsForTable(tableName: string, existingColumns: Iterable<string>): LegacyColumnDefinition[] {
  const existing = new Set(Array.from(existingColumns, (column) => column.toLowerCase()));
  const requiredColumns = legacyColumnCatalog[tableName.toLowerCase()] ?? [];

  return requiredColumns.filter((column) => !existing.has(column.name.toLowerCase()));
}

export function getRuntimeSchemaCheckTargets(): string[] {
  return [
    'integration_configs',
    'notes',
    'userTablePreferences',
    'organizationMembers',
    'staffChatMessages',
    'documents',
    'invoices',
    'users',
    'customRoles',
    'organizations',
    'payslips',
    'notifications',
    'departments',
    'jobGroups',
    'eSignatureRequests',
    'backup_history',
    'clients',
    'expenses',
    'recurringExpenses',
    'payments',
    'receipts',
    'estimates',
    'quotations',
    'contacts',
    'products',
    'services',
    'suppliers',
    'opportunities',
    'employees',
    'onboardingChecklists',
    'onboardingTasks',
    'onboardingTemplates',
    'trainingEnrollments',
    'trainingPrograms',
    'leaveRequests',
    'attendance',
    'employeeBenefits',
    'payrollDetails',
    'projectBudgets',
    'departmentBudgets',
    'creditNotes',
    'warranties',
    'lpos',
    'grnRecords',
    'serviceInvoices',
    'serviceInvoiceItems',
    'serviceTemplates',
    'emailQueue',
    'emailTemplates',
    'proposalTemplates',
    'contractTemplates',
    'scheduledJobs',
    'jobExecutionLogs',
    'jobAlertRules',
    'jobAlertHistory',
    'jobHeartbeat',
    'projects',
    'projectTasks',
    'budgetAllocations',
    'partner_profiles',
    'partner_referrals',
    'partner_commissions',
    'partner_payouts',
  ];
}

export function getMissingTableDefinitions(existingTables: Iterable<string>): LegacyTableDefinition[] {
  const existing = new Set(Array.from(existingTables, (table) => table.toLowerCase()));

  return Object.values(legacyTableCatalog).filter((table) => !existing.has(table.name.toLowerCase()));
}
